DEBUG (12/04/2024 14:37:00): server init (Line: 17 [server.py])
DEBUG (12/04/2024 14:37:05): Connection established from ('127.0.0.1', 64224) (Line: 39 [server.py])
DEBUG (12/04/2024 14:37:06): client: 127.0.0.1 - UPLOAD (Line: 205 [commands.py])
ERROR (12/04/2024 14:37:24): Connection lost with ('127.0.0.1', 64224) || Exception:[WinError 10054] Удаленный хост принудительно разорвал существующее подключение (Line: 66 [server.py])
